# Generated by Django 3.0.4 on 2020-04-16 18:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0003_auto_20200416_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=13)),
                ('message', models.TextField(blank=True, max_length=1000)),
                ('inquiry_date', models.DateTimeField(default=datetime.datetime(2020, 4, 16, 18, 53, 1, 951606, tzinfo=utc))),
                ('user_id', models.IntegerField(blank=True)),
                ('listing_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Listing')),
            ],
        ),
    ]
