# Generated by Django 3.0.4 on 2020-04-16 19:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='listing_id',
            new_name='listing',
        ),
        migrations.AlterField(
            model_name='contacts',
            name='inquiry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 18, 59, 40, 430258, tzinfo=utc)),
        ),
    ]
