# Generated by Django 3.0.4 on 2020-04-17 19:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20200416_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='inquiry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 17, 19, 49, 42, 974863, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='listing',
            field=models.CharField(max_length=100),
        ),
    ]
