# Generated by Django 3.0.4 on 2020-04-18 01:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20200418_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='listing_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='inquiry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 1, 19, 29, 153992, tzinfo=utc)),
        ),
    ]
