# Generated by Django 3.0.4 on 2020-09-03 13:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20200902_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='inquiry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 3, 13, 57, 6, 685073, tzinfo=utc)),
        ),
    ]
