# Generated by Django 3.0.4 on 2020-09-03 14:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20200903_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='inquiry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 3, 14, 42, 16, 892906, tzinfo=utc)),
        ),
    ]
