# Generated by Django 3.0.4 on 2020-04-16 18:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200324_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 16, 18, 53, 1, 948292, tzinfo=utc)),
        ),
    ]
