# Generated by Django 3.0.4 on 2020-09-02 01:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20200416_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 2, 1, 41, 48, 168510, tzinfo=utc)),
        ),
    ]
