# Generated by Django 3.0.4 on 2020-09-03 14:42

import cloudinary.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20200903_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 3, 14, 42, 16, 889334, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='', verbose_name=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='', verbose_name=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='', verbose_name=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_4',
            field=models.ImageField(blank=True, upload_to='', verbose_name=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_5',
            field=models.ImageField(blank=True, upload_to='', verbose_name=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_6',
            field=models.ImageField(blank=True, upload_to='', verbose_name=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(upload_to='', verbose_name=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
        ),
    ]
