# Generated by Django 3.0.4 on 2020-03-23 22:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('is_mvp', models.BooleanField(default=False)),
                ('hire_date', models.DateField(verbose_name=datetime.datetime(2020, 3, 23, 22, 41, 43, 696017, tzinfo=utc))),
            ],
        ),
    ]
