# Generated by Django 3.0.4 on 2020-09-03 13:57

import cloudinary.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_auto_20200902_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 3, 13, 57, 6, 598980, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
