# Generated by Django 3.0.4 on 2020-09-03 14:42

import cloudinary.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0004_auto_20200903_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 3, 14, 42, 16, 792654, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
        ),
    ]
