# Generated by Django 3.0.4 on 2020-09-03 14:53

import cloudinary.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0005_auto_20200903_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 3, 14, 53, 35, 864845, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
